// Generated by gencpp from file a5_help/RequestGoal.msg
// DO NOT EDIT!


#ifndef A5_HELP_MESSAGE_REQUESTGOAL_H
#define A5_HELP_MESSAGE_REQUESTGOAL_H

#include <ros/service_traits.h>


#include <a5_help/RequestGoalRequest.h>
#include <a5_help/RequestGoalResponse.h>


namespace a5_help
{

struct RequestGoal
{

typedef RequestGoalRequest Request;
typedef RequestGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestGoal
} // namespace a5_help


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::a5_help::RequestGoal > {
  static const char* value()
  {
    return "9befc60e44ef239556519170390f8bbe";
  }

  static const char* value(const ::a5_help::RequestGoal&) { return value(); }
};

template<>
struct DataType< ::a5_help::RequestGoal > {
  static const char* value()
  {
    return "a5_help/RequestGoal";
  }

  static const char* value(const ::a5_help::RequestGoal&) { return value(); }
};


// service_traits::MD5Sum< ::a5_help::RequestGoalRequest> should match 
// service_traits::MD5Sum< ::a5_help::RequestGoal > 
template<>
struct MD5Sum< ::a5_help::RequestGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::a5_help::RequestGoal >::value();
  }
  static const char* value(const ::a5_help::RequestGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::a5_help::RequestGoalRequest> should match 
// service_traits::DataType< ::a5_help::RequestGoal > 
template<>
struct DataType< ::a5_help::RequestGoalRequest>
{
  static const char* value()
  {
    return DataType< ::a5_help::RequestGoal >::value();
  }
  static const char* value(const ::a5_help::RequestGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::a5_help::RequestGoalResponse> should match 
// service_traits::MD5Sum< ::a5_help::RequestGoal > 
template<>
struct MD5Sum< ::a5_help::RequestGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::a5_help::RequestGoal >::value();
  }
  static const char* value(const ::a5_help::RequestGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::a5_help::RequestGoalResponse> should match 
// service_traits::DataType< ::a5_help::RequestGoal > 
template<>
struct DataType< ::a5_help::RequestGoalResponse>
{
  static const char* value()
  {
    return DataType< ::a5_help::RequestGoal >::value();
  }
  static const char* value(const ::a5_help::RequestGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // A5_HELP_MESSAGE_REQUESTGOAL_H
